### ISSUE TITLE
Need a graphical representation of the Reference Architecture

### ISSUE THREAD

**Issue by ingoa** [ncolon/ocp4-refarch#1]
Would be good to add a graphical representation of the Reference Architecture as part of the introduction.

Example would be the picture used at the implementation guide (https://blog.openshift.com/openshift-container-platform-reference-architecture-implementation-guides/ )

this one:
[Ref Arch](https://i2.wp.com/blog.openshift.com/wp-content/uploads/refarch-ocp36-on-osp10-v2.png?w=1520&ssl=1)

**Comment by ncolon** [comment]
Added sample graphic
